In [1]:
import numpy as np

In [80]:
coor = 32
img = np.arange(coor*coor).reshape(coor, coor)
print(img)

[[   0    1    2 ...   29   30   31]
 [  32   33   34 ...   61   62   63]
 [  64   65   66 ...   93   94   95]
 ...
 [ 928  929  930 ...  957  958  959]
 [ 960  961  962 ...  989  990  991]
 [ 992  993  994 ... 1021 1022 1023]]


In [75]:
x = np.array([[-1,  0,  1],
              [-2,  0,  2],
              [-1,  0,  1]])

y = np.array([[ 1, -1],
              [ 1, -1],
              [ 1, -1]])

In [71]:
def conv(img, kernel):
    final = np.zeros(img.shape)
    kernel_offset = kernel.shape[0]-2
    for i in range(kernel_offset, img.shape[0] - kernel_offset):
        for j in range(kernel_offset, img.shape[1] - kernel_offset):

            for x in range(0, kernel.shape[0], kernel.shape[0]):
                for y in range(0, kernel.shape[1], kernel.shape[1]):

                    slice = img[x:x+kernel.shape[0], y:y+kernel.shape[1]]
                    final[i][j]=(slice*(kernel)).sum()
    return final

In [82]:
print(conv(img, x))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 8. 8. ... 8. 8. 0.]
 [0. 8. 8. ... 8. 8. 0.]
 ...
 [0. 8. 8. ... 8. 8. 0.]
 [0. 8. 8. ... 8. 8. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
